### PR TITLE
I18ns the few strings I could find (including aria).

### PR DESCRIPTION
**Pull request by binarygary**

### CODE REVIEW

**Review by vegasgeek — COMMENTED** [review]
This looks OK to me, but I've added @tw2113 to the repo and have asked him to review it as well.

**Comment by tw2113** [comment]
Only real issue I have is in the details.

The first changeset spots, everything before the "Add a note" localization, should be using esc_attr__() since they're being appended to HTML attributes. The "Add a note" spot could use esc_html_e(), for escaping the incoming text, and then the one edit in class-view.php could use esc_html__().

In short, touch up some spots for escaping/i18n consistency and then a few spots for using the more appropriate escaping/i18n function.

**Comment by vegasgeek** [comment]
@tw2113 it might make more sense for you to update the pull request with the changes you're suggesting.

**Comment by tw2113** [comment]
Updated. Ready to merge whenever

**Pull request merged**
